// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ui} from '../models';
import {context} from '../models';

export function GetAudioDataURL(arg1:string):Promise<string>;

export function GetAvailablePrompts():Promise<Array<ui.PromptConfig>>;

export function GetPromptConfig(arg1:string):Promise<ui.PromptConfig>;

export function GetSelectedPrompt():Promise<string>;

export function GetSettings():Promise<ui.UISettings>;

export function IsRecording():Promise<boolean>;

export function PickModelFile():Promise<string>;

export function PickTxtFromOutDir():Promise<string>;

export function PickWavFromOutDir():Promise<string>;

export function SaveCustomPrompt(arg1:ui.PromptConfig):Promise<void>;

export function SaveSettings(arg1:string):Promise<ui.UISettings>;

export function SetSelectedPrompt(arg1:string):Promise<void>;

export function SetUIContext(arg1:context.Context):Promise<void>;

export function StartRecording(arg1:boolean):Promise<string>;

export function StartRecordingAdvanced(arg1:boolean,arg2:boolean):Promise<string>;

export function StopRecording():Promise<string>;

export function Summarise(arg1:string):Promise<string>;

export function Transcribe(arg1:string):Promise<string>;
