// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['ui']['App']['GetSettings']();
}

export function IsRecording() {
  return window['go']['ui']['App']['IsRecording']();
}

export function SaveSettings(arg1) {
  return window['go']['ui']['App']['SaveSettings'](arg1);
}

export function StartRecording(arg1) {
  return window['go']['ui']['App']['StartRecording'](arg1);
}

export function StopRecording() {
  return window['go']['ui']['App']['StopRecording']();
}

export function Summarise(arg1) {
  return window['go']['ui']['App']['Summarise'](arg1);
}

export function Transcribe(arg1) {
  return window['go']['ui']['App']['Transcribe'](arg1);
}
