// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ui} from '../models';

export function GetSettings():Promise<ui.UISettings>;

export function IsRecording():Promise<boolean>;

export function SaveSettings(arg1:string):Promise<ui.UISettings>;

export function StartRecording(arg1:boolean):Promise<string>;

export function StopRecording():Promise<string>;

export function Summarise(arg1:string):Promise<string>;

export function Transcribe(arg1:string):Promise<string>;
