// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ui} from '../models';
import {db} from '../models';
import {context} from '../models';

export function CleanupTempFiles():Promise<void>;

export function Close():Promise<void>;

export function DeleteRecording(arg1:number):Promise<void>;

export function DeleteSummary(arg1:number):Promise<void>;

export function DeleteTranscript(arg1:number):Promise<void>;

export function GetAvailablePrompts():Promise<Array<ui.PromptConfig>>;

export function GetPromptConfig(arg1:string):Promise<ui.PromptConfig>;

export function GetRecordingByID(arg1:number):Promise<db.Recording>;

export function GetRecordingFilePath(arg1:number):Promise<string>;

export function GetRecordingsWithDetails(arg1:number,arg2:number):Promise<Array<db.RecordingWithDetails>>;

export function GetRecordingsWithTranscripts():Promise<Array<db.RecordingWithTranscript>>;

export function GetRemoteConfig():Promise<ui.RemoteLLMConfig>;

export function GetSelectedPrompt():Promise<string>;

export function GetSettings():Promise<ui.UISettings>;

export function GetSummariesByTranscriptID(arg1:number):Promise<Array<db.Summary>>;

export function GetTranscriptContent(arg1:number):Promise<string>;

export function GetTranscriptsByRecordingID(arg1:number):Promise<Array<db.Transcript>>;

export function IsRecording():Promise<boolean>;

export function ListRecordings(arg1:number):Promise<Array<db.Recording>>;

export function ListRecordingsWithTranscripts():Promise<Array<db.RecordingWithDetails>>;

export function PickDatabaseFile():Promise<string>;

export function PickModelFile():Promise<string>;

export function PickTxtFromOutDir():Promise<string>;

export function PickWavFromOutDir():Promise<string>;

export function SaveCustomPrompt(arg1:ui.PromptConfig):Promise<void>;

export function SaveRemoteConfig(arg1:string):Promise<ui.RemoteLLMConfig>;

export function SaveSettings(arg1:string):Promise<ui.UISettings>;

export function SelectDatabase(arg1:string):Promise<void>;

export function SetSelectedPrompt(arg1:string):Promise<void>;

export function SetUIContext(arg1:context.Context):Promise<void>;

export function StartRecording(arg1:boolean):Promise<string>;

export function StartRecordingAdvanced(arg1:boolean,arg2:boolean):Promise<string>;

export function StartRecordingTools(arg1:boolean,arg2:boolean):Promise<string>;

export function StopRecording():Promise<string>;

export function Summarise(arg1:string):Promise<string>;

export function SummariseTranscript(arg1:number):Promise<string>;

export function Transcribe(arg1:string):Promise<string>;

export function UpdateRecording(arg1:number,arg2:Record<string, any>):Promise<void>;

export function UpdateSummary(arg1:number,arg2:Record<string, any>):Promise<void>;
